FROM openjdk:8
ADD target/AccountSystemWebSpringBoot-1.0-SNAPSHOT.war AccountSystemWebSpringBoot-1.0-SNAPSHOT.war
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "AccountSystemWebSpringBoot-1.0-SNAPSHOT.war"]
